#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Copyright (C) 2013-2023  Diego Torres Milano
Created on 2022-01-15 by Culebra v20.4.5
                      __    __    __    __
                     /  \  /  \  /  \  /  \ 
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \ 
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
"""
import threading
import time

from com.dtmilano.android.viewclient import ViewClient

TAG = 'CULEBRA'


def start_calculator():
    time.sleep(10)
    helper.target_context.start_activity('com.google.android.calculator',
                                         'com.android.calculator2.Calculator')


helper = ViewClient.view_client_helper()

threading.Thread(target=start_calculator).start()

search_condition_ref = helper.until.find_object(by_selector='text@π')
print("Let's wait until PI appears on the screen (Calculator)...")
print(helper.ui_device.wait(oid=search_condition_ref.oid, timeout=30000))
