#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import threading
import time

from com.dtmilano.android.viewclient import ViewClient


def start_calculator():
    time.sleep(10)
    helper.target_context.start_activity('com.google.android.calculator',
                                         'com.android.calculator2.Calculator')


helper = ViewClient(*ViewClient.connectToDeviceOrExit(), useuiautomatorhelper=True).uiAutomatorHelper

threading.Thread(target=start_calculator).start()

search_condition_ref = helper.until.find_object(body={'desc': 'pi'})
print("Let's wait until PI appears on the screen (Calculator)...")
print(helper.ui_device.wait(oid=search_condition_ref.oid, timeout=30000))
