#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from com.dtmilano.android.viewclient import ViewClient

helper = ViewClient.view_client_helper()

helper.target_context.start_activity('com.google.android.deskclock', 'com.android.deskclock.DeskClock')
helper.ui_device.wait_for_window_update()
alarm = helper.ui_device.find_object(body={'text': 'Alarm'}).oid
helper.ui_object2.click(alarm)
fab = helper.ui_device.find_object(body={'desc': 'Add alarm', 'res': 'com.google.android.deskclock:id/fab'}).oid
event_condition_ref = helper.until.new_window().oid
helper.ui_object2.click_and_wait(fab, event_condition_ref)
cancel = helper.ui_device.find_object(
    body={'res': 'com.google.android.deskclock:id/material_timepicker_cancel_button'}).oid
helper.ui_object2.click(cancel)
