#! /usr/bin/env python3
#
# Dumps the window hierarchy in JSON format
#

import json

from com.dtmilano.android.viewclient import ViewClient

helper = ViewClient.view_client_helper()

print(json.dumps(helper.ui_device.dump_window_hierarchy(_format='JSON').to_dict()))
