#! /usr/bin/env python3
#
# Finds the object containing a content description that matches a pattern that starts wih 'Battery',
# extracts the charging percentage, and prints it.
#

from com.dtmilano.android.viewclient import ViewClient

helper = ViewClient.view_client_helper()

obj_ref = helper.ui_device.find_object(body={'desc': 'Pattern:^Battery .*$'})
print(helper.ui_object2.dump(oid=obj_ref.oid).desc)
