#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Waits for a new toast to appear before the timeout.
# If it does then the text in the toast is printed
#

from com.dtmilano.android.viewclient import ViewClient

helper = ViewClient.view_client_helper()

print(helper.device.wait_for_new_toast(timeout=10000))
