#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Copyright (C) 2013-2019  Diego Torres Milano
Created on 2022-01-15 by Culebra v20.4.5
                      __    __    __    __
                     /  \  /  \  /  \  /  \ 
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \ 
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
"""
import threading
import time

from com.dtmilano.android.viewclient import ViewClient

TAG = 'CULEBRA'


def start_calculator():
    time.sleep(10)
    vc.uiAutomatorHelper.target_context.start_activity('com.google.android.calculator',
                                                       'com.android.calculator2.Calculator')


kwargs1 = {'verbose': False}
device, serialno = ViewClient.connectToDeviceOrExit(**kwargs1)

kwargs2 = {'useuiautomatorhelper': True, 'debug': {}}
vc = ViewClient(device, serialno, **kwargs2)

threading.Thread(target=start_calculator).start()

search_condition_ref = vc.uiAutomatorHelper.until.find_object(by_selector='text@π').oid
print("Let's wait until PI appears on the screen (Calculator)...")
print(vc.uiAutomatorHelper.ui_device.wait(search_condition_ref=search_condition_ref, timeout=30000))
