#! /usr/bin/env python3

from com.dtmilano.android.viewclient import ViewClient

helper = ViewClient(*ViewClient.connectToDeviceOrExit(), **{'useuiautomatorhelper': True}).uiAutomatorHelper

obj_ref = helper.ui_device.find_object(body={'desc': 'Pattern:^Battery .*$'})
print(helper.ui_object2.dump(oid=obj_ref.oid).desc)
