#! /usr/bin/env python3

from com.dtmilano.android.viewclient import ViewClient

device, serialno = ViewClient.connectToDeviceOrExit()

print('Top Activity:', device.getTopActivityName())
print('URI:', device.getTopActivityUri())
