#! /usr/bin/env python3
# -*- coding: utf-8 -*-

try:
    import os
    import sys
    sys.path.insert(0, os.path.join(os.environ['ANDROID_VIEW_CLIENT_HOME'], 'src'))
except:
    pass

from com.dtmilano.android.viewclient import ViewClient

vc = ViewClient(*ViewClient.connectToDeviceOrExit(), useuiautomatorhelper=True)

print(vc.uiAutomatorHelper.device.wait_for_new_toast(timeout=10000))
