#! /usr/bin/env python

import sys

from com.dtmilano.android.viewclient import ViewClient

if len(sys.argv) < 6:
    sys.exit("usage: %s left top right bottom filename.png [serialno]" % sys.argv[0])

left = int(sys.argv.pop(1))
top = int(sys.argv.pop(1))
right = int(sys.argv.pop(1))
bottom = int(sys.argv.pop(1))
filename = sys.argv.pop(1)
device, serialno = ViewClient.connectToDeviceOrExit()
device.takeSnapshot(box=(left, top, right, bottom)).save(filename, 'PNG')
